### ISSUE TITLE
Why do I get an error when loading weights while pruning

### ISSUE THREAD

**Issue by shand12** [YellowPancake/TCIL#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/usr/local/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/usr/local/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/usr/local/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/content/drive/MyDrive/TCIL-main/main.py", line 306, in prune
    tmodel._parallel_network.load_state_dict(state_dict)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.convnets.0.conv1.0.weight: copying a param with shape torch.Size([58, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]).
	size mismatch for module.convnets.0.conv1.1.weight: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.conv1.1.bias: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.conv1.1.running_mean: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.conv1.1.running_var: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.0.conv1.weight: copying a param with shape torch.Size([58, 58, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for module.convnets.0.layer1.0.bn1.weight: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.0.bn1.bias: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.0.bn1.running_mean: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.0.bn1.running_var: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.0.conv2.weight: copying a param with shape torch.Size([58, 58, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for module.convnets.0.layer1.0.bn2.weight: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.0.bn2.bias: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.0.bn2.running_mean: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.0.bn2.running_var: copying a param with shape torch.Size([58]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.convnets.0.layer1.1.conv1.weight: copying a param with shape torch.Size([52, 58, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3])

**Comment by YellowPancake** [comment]
The model's structure has been altered by pruning. Therefore, attempting to load the saved parameters directly onto the original model will lead to the mismatch error. Since test accuracy were generated during the training phase, there was no dedicated testing function written for pruning. You can evaluate the pruned model by the following steps:

1. Omit the model training function in  main.py [line 322](https://github.com/YellowPancake/TCIL/blob/de320bf85b86f991275bcc4f0ac20100efbb67e6/main.py#L322C6-L322C6)
2. Instead, use the following command to load the trained parameters:
`
        state_dict = torch.load(f'{save_path}/prune_step{taski}.ckpt')
        model._parallel_network.load_state_dict(state_dict)
`
