### ISSUE TITLE
Where is the code setting for rehearsal strategy?

### ISSUE THREAD

**Issue by WF-CIL** [YellowPancake/TCIL#2]
Hello, your paper mentions whether to use rehearsal strategy to train the model. Where is the code setting for rehearsal strategy?

**Comment by WF-CIL** [comment]
Is it to set the 'memory_size' parameter in YAML to 0?

**Comment by YellowPancake** [comment]
As you said, just add 'memory_size' to 0 is the task setting for none-rehearsal strategy. You can test the performance of TCIL under different exemplar numbers by changing 'memory_size'.
